---
name: Checks

on: [push]
jobs:
  
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: eslint cypress . --ext .js,.jsx,.ts,.tsx

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5